### ISSUE TITLE
Something in the clone method broke in 1.3.0

### ISSUE THREAD

**Issue by Rantanen** [75lb/object-tools#2]
jsdoc-parse now fails when cloning _class somewhere in `transform.js` and then trying to access its `classdesc` as `object-tools.clone()` returns undefined.

I'll get the error traces soon.

**Comment by 75lb** [comment]
Eek, I will look asap

**Comment by Rantanen** [comment]
```
/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/lib/transform.js:85
    if (class_.classdesc){
              ^
TypeError: Cannot read property 'classdesc' of undefined
    at createConstructor (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/lib/transform.js:85:15)
    at /home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/lib/transform.js:108:54
    at Array.forEach (native)
    at Object.insertConstructors (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/lib/transform.js:106:10)
    at Object.exports.publish (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/lib/publish.js:18:22)
    at Object.module.exports.cli.generateDocs (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/cli.js:433:39)
    at Object.module.exports.cli.processParseResults (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/cli.js:386:20)
    at module.exports.cli.main (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/cli.js:230:14)
    at Object.module.exports.cli.runCommand (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/cli.js:183:5)
    at /home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/jsdoc.js:134:13
    at Object.<anonymous> (/home/wace/projects/node-mumble/node_modules/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-75lb/jsdoc.js:136:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unexpected end of input
```

**Comment by Rantanen** [comment]
Actually not sure if this is from Typical. Trying to work out a minimal reproduction case.

**Comment by 75lb** [comment]
do you have the latest version of the tool installed? i'm trying and failing to reproduce this..

**Comment by 75lb** [comment]
now i can reproduce..

**Comment by Rantanen** [comment]
It failed on a new Travis-CI build, so everything should be up to date:

https://travis-ci.org/Rantanen/node-mumble/builds/62273909

Just tested it by starting the previously successful build, which failed now:

https://travis-ci.org/Rantanen/node-mumble/builds/62267068

**Comment by 75lb** [comment]
fixed in object-tools@1.3.1 - thanks for the quick report!

**Comment by 75lb** [comment]
please reinstall the tool/plugin

**Comment by Rantanen** [comment]
The builds on Travis are succeeding now. Thanks!
